# Generated by Django 3.0.4 on 2020-04-03 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
    ]
