# Generated by Django 3.0.4 on 2020-04-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200403_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='rate',
            field=models.DecimalField(decimal_places=1, max_digits=1),
        ),
    ]
