# Generated by Django 3.0.5 on 2020-05-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmetApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
