# Generated by Django 3.0.4 on 2020-04-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.IntegerField(default=1),
        ),
    ]
